### ISSUE TITLE
Update archive after adding a .datignore

### ISSUE THREAD

**Issue by AlbertoElias** [joehand/dat-ignore#4]
Hey, I had a previously created archive, and then added a `.datignore` file,  how would I create a new version of that archive with the now ignored files not appearing? Thanks!

**Comment by joehand** [comment]
Hey @AlbertoElias, the only way right now is to probably create a new archive. You can do this by deleting the `.dat` folder. 

Unfortunately there is not any way to remove the files from the existing archive metadata.

**Comment by AlbertoElias** [comment]
Ok! Thank you very much!
